# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cdl
canonical: https://interop.esante.gouv.fr/ig/fhir/cdl # the last part of canonical and id must be the same
name: CDL
title: Cahier De Liaison
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'

dependencies:
  ans.fhir.fr.annuaire: 1.0.1
  hl7.fhir.fr.core: 2.0.1
  ans.fr.nos: latest

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Spécifications fonctionnelles
    specifications_techniques.md:
        construction_des_flux.md:
        st_flux1.md:
            title: Flux 01
        st_flux2.md:
            title: Flux 02

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Construction des flux: construction_des_flux.html
        Flux 01: st_flux1.html
        Flux 02: st_flux2.html
    Ressources de conformité: artifacts.html
    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation