# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cdl
canonical: https://interop.esante.gouv.fr/ig/fhir/cdl # the last part of canonical and id must be the same
name: CDL
title: Cahier De Liaison
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'

dependencies:
  ans.fhir.fr.annuaire: 1.0.1
  hl7.fhir.fr.core: 2.0.1
  ans.fr.nos: latest

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Spécifications fonctionnelles
    specifications_techniques.md:
        construction_des_flux.md:
        creation_note.md:
            title: Création d'une note
        maj_note.md:
            title: M-à-j d'une note
        suppr_note.md:
            title: Suppression d'une note
        recherche_note.md:
            title: Recherche d'une note
menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Construction des flux: construction_des_flux.html
        Création d'une note: creation_note.html
        M-à-j d'une note: maj_note.html
        Suppression d'une note: suppr_note.html
        Recherche d'une note: recherche_note.html
    Ressources de conformité: artifacts.html
    Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation